### ISSUE TITLE
0.4.1 (from PyPI) is broken: No such file or directory:  ... /README.md

### ISSUE THREAD

**Issue by yurivict** [pr-omethe-us/PyKED#131]
It attempts to open a non-existent file:
```
===>  Configuring for py38-pyked-0.4.1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 11, in <module>
    with open(path.join(here, 'README.md')) as readme_file:
  File "/usr/local/lib/python3.8/codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/disk-samsung/freebsd-ports/science/py-pyked/work-py38/pyked-0.4.1/README.md'
*** Error code 1
```

**Comment by bryanwweber** [comment]
Yep, probably a problem with the MANIFEST.in file, which would need to include the `README.md` file. Please feel free to submit a pull request to fix it.

**Comment by yurivict** [comment]
The current GH master doesn't have this problem.
